version: '3.8'

services:
  gateway:
    image: nginx:alpine
    # container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/conf.d:/etc/nginx/conf.d:ro 
      - ./gateway/certs:/etc/nginx/certs:ro
    depends_on:
      - user-service
      - email-service
      - inventory-service
      - payment-service  

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - kafka

  email-service:
    env_file:
      - ./email-service/.env
    build:
      context: ./email-service
      dockerfile: Dockerfile
    # container_name: email_service
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - KAFKA_BROKER=kafka:9092 
    depends_on:
      - redis
      - kafka

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    # container_name: redis_queue_2
    ports:
      - "6379:6379"
  
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://${INVENTORY_DB_USER}:${INVENTORY_DB_PASSWORD}@inventory_db:5432/${INVENTORY_DB_NAME}
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://${INVENTORY_DB_USER}:${INVENTORY_DB_PASSWORD}@inventory_db:5432/${INVENTORY_DB_NAME}
      - KAFKA_BROKER=kafka:9092
      - REDIS_HOST=redis
    depends_on:
      - inventory_db
      - kafka
      - redis

  inventory_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=${INVENTORY_DB_NAME}
      - POSTGRES_USER=${INVENTORY_DB_USER}
      - POSTGRES_PASSWORD=${INVENTORY_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - inventory_pg_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    # container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    # container_name: kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    # container_name: payment_service
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - KAFKA_BROKER=kafka:9092
      - REDIS_HOST=redis
    depends_on:
      - kafka
      - redis

volumes:
  postgres_data:
  inventory_pg_data:
  kafka_data: